title: Sourish Kumrawat
description: Mathematics, machine learning, and scientific computing.
url: ""
baseurl: ""

permalink: pretty
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - vendor_pkgs
  - .vendor
  - elan_installer
  - elan.zip
